name: aspects-poc-reporting
base: core22
version: "0.1"
license: GPL-2.0-only
summary: Snap that consumes aspects config.
description: |
  This snap collects metrics from the device and reports them
  every minute.

grade: devel
confinement: devmode

environment:
  ACCOUNT_ID: f22PSauKuNkwQTM9Wz67ZCjNACuSjjhN

apps:
  daemon:
    command: bin/reporter-cli
    daemon: oneshot
    timer: 00:00-24:00/1440  # every minute

parts:
  reporter:
    plugin: python
    source: .
    parse-info:
      - setup.py
    python-packages:
      - snap-http==1.4.0
